version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      # This second volume is important to prevent a common Vite issue in Docker
      - /app/node_modules

  backend:
    build: ./backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  order_processor:
    build: ./workers/order_processor
    env_file:
      - ./.env
    volumes:
      - ./workers/order_processor:/app
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.13-management
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
